language: php

php:
  - "5.5"
  - "5.6"

before_script:
  - composer install

script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml

after_script:
  - travis_retry php vendor/bin/coveralls -v
